// constants.js
export const COUNTRIES = [
    "United States",
    "Canada",
    "Colombia",
    "Mexico",
    "United Kingdom",
    "Germany",
    "France",
    "Spain",
    "Italy",
    "Australia",
    "Brazil",
    "Argentina",
    "China",
    "India",
    "Japan",
    "South Korea",
    "South Africa",
    "Russia",
    "Costa Rica",
    "Venezuela",
];
