"""empty message

Revision ID: 0637e29ff5aa
Revises: ee05cf062a72
Create Date: 2024-11-11 03:18:26.681499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0637e29ff5aa'
down_revision = 'ee05cf062a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
