"""empty message

Revision ID: 269f0be2b316
Revises: ae777929dac0
Create Date: 2024-10-31 02:21:02.868763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269f0be2b316'
down_revision = 'ae777929dac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imageb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imageb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='imageb_pkey')
    )
    # ### end Alembic commands ###
