"""empty message

Revision ID: 34137192fbad
Revises: bcd2191b358b
Create Date: 2024-10-23 15:39:04.215722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34137192fbad'
down_revision = 'bcd2191b358b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_donor')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    op.create_table('login_donor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='login_donor_pkey'),
    sa.UniqueConstraint('email', name='login_donor_email_key')
    )
    # ### end Alembic commands ###
