"""empty message

Revision ID: 382c8b4b7a64
Revises: 
Create Date: 2024-10-19 23:12:40.167146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382c8b4b7a64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('wish_gift', sa.String(length=250), nullable=True),
    sa.Column('history', sa.String(length=250), nullable=True),
    sa.Column('account', sa.String(length=250), nullable=False),
    sa.Column('picture', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('beneficiary')
    # ### end Alembic commands ###
