"""empty message

<<<<<<<< HEAD:migrations/versions/5eb57b272d7e_.py
Revision ID: 5eb57b272d7e
Revises: 
Create Date: 2024-10-20 16:09:00.917464
========
Revision ID: 564e0cc90a70
Revises: 
Create Date: 2024-10-22 01:03:46.275041
>>>>>>>> develop:migrations/versions/564e0cc90a70_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/5eb57b272d7e_.py
revision = '5eb57b272d7e'
========
revision = '564e0cc90a70'
>>>>>>>> develop:migrations/versions/564e0cc90a70_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('wish_gift', sa.String(length=250), nullable=True),
    sa.Column('history', sa.String(length=250), nullable=True),
    sa.Column('account', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('donor')
    op.drop_table('beneficiary')
    # ### end Alembic commands ###
