"""empty message

Revision ID: 769ea6b12f53
Revises: 4cadd74a8e69
Create Date: 2024-11-02 00:12:29.185258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769ea6b12f53'
down_revision = '4cadd74a8e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_help',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_foundation', sa.Integer(), nullable=True),
    sa.Column('id_beneficiary', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_beneficiary'], ['beneficiary.id'], ),
    sa.ForeignKeyConstraint(['id_foundation'], ['foundation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_help')
    # ### end Alembic commands ###
