"""empty message

Revision ID: 801944055b74
Revises: 67dd25956faf
Create Date: 2024-10-26 22:44:23.783112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801944055b74'
down_revision = '67dd25956faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imageb', schema=None) as batch_op:
        batch_op.drop_constraint('imageb_email_key', type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imageb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('imageb_email_key', ['email'])

    # ### end Alembic commands ###
