"""empty message

Revision ID: 8a853d0db67b
Revises: 769ea6b12f53
Create Date: 2024-11-04 05:42:52.570456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a853d0db67b'
down_revision = '769ea6b12f53'
branch_labels = None
depends_on = None


def upgrade():
    # Agrega la columna `is_active` con `nullable=True` inicialmente
    with op.batch_alter_table('foundation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # Asigna el valor `True` a `is_active` en todos los registros existentes
    op.execute("UPDATE foundation SET is_active = TRUE WHERE is_active IS NULL")

    # Aplica la restricción `NOT NULL` a `is_active`
    with op.batch_alter_table('foundation', schema=None) as batch_op:
        batch_op.alter_column('is_active', nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foundation', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
