"""empty message

Revision ID: a84a894e2528
Revises: 382c8b4b7a64
Create Date: 2024-10-19 23:25:20.009848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84a894e2528'
down_revision = '382c8b4b7a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Boolean(),
               nullable=False)
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
