"""empty message

<<<<<<<< HEAD:migrations/versions/bcd2191b358b_.py
Revision ID: bcd2191b358b
Revises: 
Create Date: 2024-10-23 13:59:25.127273
========
Revision ID: 67dd25956faf
Revises: 
Create Date: 2024-10-26 22:34:55.788836
>>>>>>>> develop:migrations/versions/67dd25956faf_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/bcd2191b358b_.py
revision = 'bcd2191b358b'
========
revision = '67dd25956faf'
>>>>>>>> develop:migrations/versions/67dd25956faf_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('wish_gift', sa.String(length=250), nullable=True),
    sa.Column('history', sa.String(length=250), nullable=True),
    sa.Column('account', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
<<<<<<<< HEAD:migrations/versions/bcd2191b358b_.py
    op.create_table('login_donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
========
    op.create_table('foundation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('country', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imageb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
>>>>>>>> develop:migrations/versions/67dd25956faf_.py
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
<<<<<<<< HEAD:migrations/versions/bcd2191b358b_.py
    op.drop_table('login_donor')
========
    op.drop_table('imageb')
    op.drop_table('foundation')
>>>>>>>> develop:migrations/versions/67dd25956faf_.py
    op.drop_table('donor')
    op.drop_table('beneficiary')
    # ### end Alembic commands ###
