"""empty message

Revision ID: cbcd42d8ad5c
Revises: dc70ccd72029
Create Date: 2024-11-11 02:13:39.128877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcd42d8ad5c'
down_revision = 'dc70ccd72029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_help')
    op.drop_table('user')
    with op.batch_alter_table('foundation', schema=None) as batch_op:
        batch_op.alter_column('donor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foundation', schema=None) as batch_op:
        batch_op.alter_column('donor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_table('post_help',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_foundation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_beneficiary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_beneficiary'], ['beneficiary.id'], name='post_help_id_beneficiary_fkey'),
    sa.ForeignKeyConstraint(['id_foundation'], ['foundation.id'], name='post_help_id_foundation_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_help_pkey')
    )
    # ### end Alembic commands ###
