"""empty message

Revision ID: e8004ce77428
Revises: 70b43ea7c634
Create Date: 2024-11-07 02:30:02.107235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8004ce77428'
down_revision = '70b43ea7c634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foundation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foundation', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
