"""empty message

Revision ID: e96f496ebf1a
Revises: 5ea3d0caa72a
Create Date: 2024-10-21 22:17:11.631592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96f496ebf1a'
down_revision = '5ea3d0caa72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foundation',
    sa.Column('Foundation_ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=250), nullable=False),
    sa.Column('Description', sa.String(length=250), nullable=False),
    sa.Column('Country', sa.String(length=250), nullable=False),
    sa.Column('Email', sa.String(length=250), nullable=False),
    sa.Column('Password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('Foundation_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foundation')
    # ### end Alembic commands ###
